### ISSUE TITLE
Experimental software and hardware setup details

### ISSUE THREAD

**Issue by xkhainguyen** [vivek-uka/AMSwarm#1]
Hi, 

I find your project very interesting. From what I understand, you will compute the position and velocity trajectory on a single station and then send it to each drone. 

Then I am curious about the setup (software and hardware) for communication like feedback, commands, etc. Could you please briefly describe it for me so I would be able to run the pipeline on my own?

Thank you very much!

**Comment by vivek-uka** [comment]
We showcase our algorithm using a Crazyflie swarm testbed that operates within a motion capture system. Here's the basic sequence: 
- The motion capture system tracks the drones' positions (single marker).
- On a laptop, we compute the estimated position and velocity of each drone.
- We run our planner (launching threads for each drone) on the laptop to generate a trajectory.
- Position and velocity commands are sent to the lower-level controller via radio communication.
This entire process repeats. One may use [Crazyswarm package](https://crazyswarm.readthedocs.io/en/latest/), which handles the second and fourth steps.

Here's a bit more detail: 
- We use an event-triggered replanning strategy (see [Section IV](https://arxiv.org/pdf/1909.05150.pdf)).  Based on the tracking error, the strategy decides whether to set the actual state of the drone as initial conditions or assume the last commanded state has been achieved. This strategy results in smooth reference input to the lower controller. 
 
- After generating a trajectory at a planning step, we upsample the trajectory at a resolution of 0.01 seconds. We then send the first six sets of position and velocity commands to the Mellinger controller at a rate of 60 Hz. This cycle repeats for each planning step. You can access the upsampled trajectory from the `prob_data.x_up`, `prob_data.xdot_up` variables.

I hope this helps!
Vivek.
